name       : "ClassesFightArena"
main: "Main"
version    : "0.24"
api-version: "1.17"
depend     : [ "EternaAPI" ]
authors    : [ "Plugin Developer: hapyl", "Design/Idea: sdimas74", "Design/Builder: DirtyEl", "idk he just a noob: DiDenPro" ]